-- ============================================================
-- EMPLOYEE MASTER & LOGIN
-- ============================================================

CREATE TABLE mfg.employees (
    employee_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    int8 NOT NULL,
    employee_code varchar(50) NOT NULL,
    employee_name varchar(255) NOT NULL,
    phone         varchar(20) NULL,
    email         varchar(255) NULL,
    designation   varchar(100) NULL,
    joined_dt     date NULL,
    is_active     bool NOT NULL DEFAULT true,
    created_by    int8 NOT NULL,
    created_dt    timestamp(6) NOT NULL,
    modified_by   int8 NULL,
    modified_dt   timestamp(6) NULL,
    CONSTRAINT uk_emp_code UNIQUE (company_id, employee_code),
    CONSTRAINT fk_emp_company FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);

CREATE TABLE mfg.employee_portal_users (
    portal_user_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    int8 NOT NULL,
    company_id     int8 NOT NULL,
    username       varchar(100) NOT NULL,
    password       varchar(300) NOT NULL,
    last_login_dt  timestamp(6) NULL,
    is_active      bool NOT NULL DEFAULT true,
    created_dt     timestamp(6) NOT NULL,
    modified_dt    timestamp(6) NULL,
    CONSTRAINT uk_portal_username UNIQUE (username),
    CONSTRAINT fk_epu_employee FOREIGN KEY (employee_id) REFERENCES mfg.employees(employee_id),
    CONSTRAINT fk_epu_company  FOREIGN KEY (company_id)  REFERENCES public.companies(company_id)
);

-- ============================================================
-- SALARY CONFIG — versioned, not overwritten
-- ============================================================

CREATE TABLE mfg.employee_salary_config (
    config_id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id    int8 NOT NULL,
    salary_type    varchar(20) NOT NULL,   -- MONTHLY | WORK_BASED
    monthly_amount numeric(38,2) NULL,     -- only for MONTHLY
    effective_from date NOT NULL,
    effective_to   date NULL,              -- NULL = current active config
    created_by     int8 NOT NULL,
    created_dt     timestamp(6) NOT NULL,
    CONSTRAINT chk_salary_type CHECK (salary_type IN ('MONTHLY','WORK_BASED')),
    CONSTRAINT fk_esc_employee FOREIGN KEY (employee_id) REFERENCES mfg.employees(employee_id)
);
CREATE INDEX idx_esc_employee ON mfg.employee_salary_config(employee_id, effective_from);

-- ============================================================
-- WORK DEFINITIONS — admin configures, fully flexible
-- ============================================================

CREATE TABLE mfg.work_definitions (
    work_def_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    company_id    int8 NOT NULL,
    work_name     varchar(255) NOT NULL,
    work_code     varchar(50) NOT NULL,
    description   text NULL,
    rate_per_unit numeric(38,2) NOT NULL,
    unit          varchar(20) NOT NULL,    -- KG | PC | BOX | LITER | METER | HOUR
    is_active     bool NOT NULL DEFAULT true,
    created_by    int8 NOT NULL,
    created_dt    timestamp(6) NOT NULL,
    modified_by   int8 NULL,
    modified_dt   timestamp(6) NULL,
    CONSTRAINT uk_work_code UNIQUE (company_id, work_code),
    CONSTRAINT chk_work_unit CHECK (unit IN ('KG','PC','BOX','LITER','METER','GRAM','HOUR')),
    CONSTRAINT fk_wd_company FOREIGN KEY (company_id) REFERENCES public.companies(company_id)
);

-- Rate change history — old logs keep rate_snapshot, so this is for audit
CREATE TABLE mfg.work_definition_rate_history (
    rate_history_id int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    work_def_id     int8 NOT NULL,
    rate_per_unit   numeric(38,2) NOT NULL,
    unit            varchar(20) NOT NULL,
    effective_from  date NOT NULL,
    effective_to    date NULL,
    changed_by      int8 NOT NULL,
    changed_dt      timestamp(6) NOT NULL,
    CONSTRAINT fk_wdrh_work_def FOREIGN KEY (work_def_id) REFERENCES mfg.work_definitions(work_def_id)
);

-- ============================================================
-- DAILY WORK LOG — entered by employee via portal
-- ============================================================

CREATE TABLE mfg.employee_work_logs (
    log_id           int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id      int8 NOT NULL,
    company_id       int8 NOT NULL,
    work_def_id      int8 NOT NULL,
    log_date         date NOT NULL,
    quantity         numeric(38,2) NOT NULL,
    unit             varchar(20) NOT NULL,     -- snapshot at log time
    rate_snapshot    numeric(38,2) NOT NULL,   -- rate locked at log time — never changes
    amount_earned    numeric(38,2) NOT NULL,   -- quantity × rate_snapshot, stored
    employee_remarks text NULL,
    status           varchar(20) NOT NULL DEFAULT 'PENDING',
    reviewed_by      int8 NULL,
    reviewed_dt      timestamp(6) NULL,
    admin_remarks    text NULL,
    created_dt       timestamp(6) NOT NULL,
    modified_dt      timestamp(6) NULL,
    CONSTRAINT chk_ewl_status CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT fk_ewl_employee FOREIGN KEY (employee_id) REFERENCES mfg.employees(employee_id),
    CONSTRAINT fk_ewl_company  FOREIGN KEY (company_id)  REFERENCES public.companies(company_id),
    CONSTRAINT fk_ewl_work_def FOREIGN KEY (work_def_id) REFERENCES mfg.work_definitions(work_def_id)
);
CREATE INDEX idx_ewl_employee_date ON mfg.employee_work_logs(employee_id, log_date);
CREATE INDEX idx_ewl_period        ON mfg.employee_work_logs(company_id, log_date, status);

-- ============================================================
-- LEAVE LOG — monthly salary employees only
-- ============================================================

CREATE TABLE mfg.employee_leave_logs (
    leave_id      int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id   int8 NOT NULL,
    company_id    int8 NOT NULL,
    leave_date    date NOT NULL,
    leave_type    varchar(20) NOT NULL DEFAULT 'FULL_DAY',  -- FULL_DAY | HALF_DAY
    leave_category varchar(20) NOT NULL DEFAULT 'CASUAL',  -- CASUAL | SICK | UNPAID | LOP
    reason        text NULL,
    status        varchar(20) NOT NULL DEFAULT 'PENDING',  -- PENDING | APPROVED | REJECTED
    approved_by   int8 NULL,
    approved_dt   timestamp(6) NULL,
    created_dt    timestamp(6) NOT NULL,
    CONSTRAINT chk_leave_type CHECK (leave_type IN ('FULL_DAY','HALF_DAY')),
    CONSTRAINT chk_leave_cat  CHECK (leave_category IN ('CASUAL','SICK','UNPAID','LOP')),
    CONSTRAINT chk_leave_stat CHECK (status IN ('PENDING','APPROVED','REJECTED')),
    CONSTRAINT uk_leave_date  UNIQUE (employee_id, leave_date),
    CONSTRAINT fk_ell_employee FOREIGN KEY (employee_id) REFERENCES mfg.employees(employee_id),
    CONSTRAINT fk_ell_company  FOREIGN KEY (company_id)  REFERENCES public.companies(company_id)
);

-- ============================================================
-- MONTH-END SALARY COMPUTATION
-- ============================================================

CREATE TABLE mfg.employee_salary_periods (
    salary_period_id   int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    employee_id        int8 NOT NULL,
    company_id         int8 NOT NULL,
    period             bpchar(6) NOT NULL,       -- YYYYMM
    salary_type        varchar(20) NOT NULL,     -- snapshot: MONTHLY | WORK_BASED
    working_days_in_month int4 NULL,
    days_present       numeric(5,1) NULL,        -- for monthly
    days_absent        numeric(5,1) NULL,        -- for monthly
    lop_days           numeric(5,1) NULL DEFAULT 0,
    gross_amount       numeric(38,2) NOT NULL,
    lop_deduction      numeric(38,2) NOT NULL DEFAULT 0,
    other_deductions   numeric(38,2) NOT NULL DEFAULT 0,
    net_amount         numeric(38,2) NOT NULL,
    status             varchar(20) NOT NULL DEFAULT 'DRAFT',
    approved_by        int8 NULL,
    approved_dt        timestamp(6) NULL,
    paid_dt            timestamp(6) NULL,
    payment_ref        varchar(100) NULL,
    computed_dt        timestamp(6) NOT NULL,
    created_dt         timestamp(6) NOT NULL,
    CONSTRAINT uk_salary_period UNIQUE (employee_id, period),
    CONSTRAINT chk_sp_status CHECK (status IN ('DRAFT','APPROVED','PAID')),
    CONSTRAINT fk_sp_employee FOREIGN KEY (employee_id) REFERENCES mfg.employees(employee_id),
    CONSTRAINT fk_sp_company  FOREIGN KEY (company_id)  REFERENCES public.companies(company_id)
);

-- Line items — one row per work type for WORK_BASED,
-- one FIXED + DEDUCTION/BONUS rows for MONTHLY
CREATE TABLE mfg.employee_salary_lines (
    line_id          int8 GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    salary_period_id int8 NOT NULL,
    work_def_id      int8 NULL,          -- NULL for FIXED / DEDUCTION / BONUS lines
    line_type        varchar(20) NOT NULL,
    -- FIXED | WORK_EARNING | DEDUCTION | BONUS
    description      varchar(255) NOT NULL,
    total_qty        numeric(38,2) NULL,  -- work-based only
    unit             varchar(20) NULL,    -- work-based only
    rate_used        numeric(38,2) NULL,  -- work-based only
    amount           numeric(38,2) NOT NULL,
    CONSTRAINT chk_sl_type CHECK (line_type IN ('FIXED','WORK_EARNING','DEDUCTION','BONUS')),
    CONSTRAINT fk_sl_period   FOREIGN KEY (salary_period_id) REFERENCES mfg.employee_salary_periods(salary_period_id),
    CONSTRAINT fk_sl_work_def FOREIGN KEY (work_def_id)      REFERENCES mfg.work_definitions(work_def_id)
);